name: Release website

on:
  push:
    branches:
      - main
    paths:
      - "applications/website/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: yarn

      - name: Install Dependencies
        run: yarn --cwd ./applications/website

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          cwd: ./applications/website
          title: Version Website
          version: yarn run version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
